# TODO: Replace these placeholder values with your actual AWS account IDs and region
pipelineAccount:
  awsAccountId: YOUR_PIPELINE_ACCOUNT_ID
  awsRegion: YOUR_PREFERRED_REGION

devAccount:
  awsAccountId: YOUR_DEV_ACCOUNT_ID
  awsRegion: YOUR_PREFERRED_REGION

prodAccount:
  awsAccountId: YOUR_PROD_ACCOUNT_ID
  awsRegion: YOUR_PREFERRED_REGION

dev:
  jobs:
    ProcessLegislators:
      inputLocation: s3://awsglue-datasets/examples/us-legislators/all/persons.json

prod:
  jobs:
    ProcessLegislators:
      inputLocation: s3://awsglue-datasets/examples/us-legislators/all/persons.json